### ISSUE TITLE
hypergeometric0F1(double, double) improve precision?

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#12]
Can you please compare, if you would back port the following commit:
- https://github.com/axkr/symja_android_library/commit/bdb7a50573e5a051be3c18ede57c6e28489697ff

gives a better precision for your `hypergeometric0F1()` implementation?
https://github.com/paulmasson/math/blob/de987ba818a46d33d55e73cccebcbf4758bb43ef/src/functions/hypergeometric.js#L114

The Java implementation uses:
- max iteration 500
- tolerance 5.E-14
- method hasReachedAccuracy

Is the performance the same?

**Comment by paulmasson** [comment]
@axkr since I'm developing with browser-based interactions in mind, I decided long ago that ten decimal places are plenty for me. That's enough to show that the methods are accurate. I could gain a few more digits by altering the default tolerance but it would slow applications down.

By checking both accuracy and number of terms in your version, you're doing extra work that isn't needed in practice. As long as you're switching to the asymptotic form things converge rapidly, so you shouldn't need to check the number of terms.

In my initial version of this file I used relative accuracy but found that created problems in dependent functions, like `besselK`. Seems to me so far that absolute accuracy is better in these calculations.

You should also know that the reason I wrote `hypergeometricSeries` was to consolidate code in this file. I plan to use it for all of the hypergeometric functions but want to see how much of a performance hit I get from accessing values in arrays vs. regular declared variables. I know from testing it will be a bit slower but would still like to have the cleaner code. Don't know if that would be a problem in Java or not.

**Comment by paulmasson** [comment]
Need to backtrack on last comment: will not be using `hypergeometricSeries` by default. Besides the performance hit I know will happen, `hypergeometric2F01` is more finicky than I remembered. Formally divergent series like that one need an explicit check for convergence so needs to stay separate for now.

**Comment by paulmasson** [comment]
@axkr since this library has had the option of arbitrary precision implementation for some time, and is actually used internally in `hypergeometric1F1`, I'm closing this issue. At some point it would be nice to allow all functions to return arbitrary precision results if desired.
