### ISSUE TITLE
Gudermannian

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#24]
Can you define it for complex number too?

The formula `2*arctan(tanh(z/2))` seems to be better suited for complex arg.

- https://en.wikipedia.org/wiki/Gudermannian_function

![grafik](https://user-images.githubusercontent.com/3109793/116433578-edc32400-a849-11eb-865a-9f47db7773de.png)

Same for the inverse?

![grafik](https://user-images.githubusercontent.com/3109793/116437076-56f86680-a84d-11eb-9b0d-1474cf592776.png)

If you get a NaN for double values you can  try complex evaluation as fallback.

**Comment by paulmasson** [comment]
@axkr I'm not understanding the issue: both functions are already complex, if you input a complex argument. Have you found explicit cases that are incorrect?

**Comment by axkr** [comment]
The results of these 2 cases can be improved ?

```
console.log( inverseGudermannian(3.75) );
console.log( gudermannian(complex(5.0,Math.Pi)) );
```

**Comment by paulmasson** [comment]
@axkr sorry I've neglected this issue for so long. Comparing these two expressions in Mathematica

```
Gudermannian[5. + Pi I]
ArcTan[Tanh[(5 + Pi I)/2]]
```

gives different answers, so it's not as simple as changing to that expression. In fact Mathematica appears to be using `2 ArcTan[Exp[x]] - Pi/2` but I need to research this more.

**Comment by paulmasson** [comment]
Just plotted four different expressions for this function over the complex plane, and no obvious way to choose which one should be used.

Mathematica's online documentation says the function is given by `2 arctan(tanh(z/2))`, but `FunctionExpand` on WolframAlpha returns `2 arctan(exp(z)) - pi/2`. The imaginary parts of the two expressions appear to be identical, but the real part is wildly different in the right-hand complex plane.

Needs more thought...

**Comment by paulmasson** [comment]
@axkr it occurred to me yesterday that I can simply evaluate the integral definition of the Gudermannian on the complex plane and compare it to various expressions. [Turns out](https://analyticphysics.com/Complex%20Variables/The%20Complex%20Gudermannian%20Function.htm) the expression you suggested at the beginning of this thread is the correct one. Don't know why Mathematica doesn't follow its own documentation...

**Comment by paulmasson** [comment]
@axkr fixed in 5559263. Thanks for the input!

**Comment by jrus** [comment]
I’ve been working on the [Wikipedia article](https://en.wikipedia.org/wiki/Gudermannian_function) a bit so it should hopefully be a bit clearer now. The $z \mapsto 2 \operatorname{atan}(\tanh\tfrac12z)$ variant is clearly correct while the others listed are wrong (for complex $z$).

(It is true that $\sin \operatorname{gd} z = \tanh z$ etc., but you can’t compute it that way without careful choice of branch on the inverse trig functions.)

There’s also another way to do this computation directly in components, which should work out the same as $2 \operatorname{atan}(\tanh\tfrac12z)$ if you use the 2-argument arctan: 

If $u + iv = \operatorname{gd}(x + iy),$ then $u = \operatorname{atan2}(\sinh x, \cos y),$ $v = \operatorname{atanh}(\sin y \ / \cosh x).$

And in the inverse direction, $x = \operatorname{atanh}(\sin u \ / \cosh v),$ $y =  \operatorname{atan2}(\sinh v, \cos u).$

Bonus figures:
![](https://upload.wikimedia.org/wikipedia/commons/c/c0/Gudermannian_identities.png)
![](https://upload.wikimedia.org/wikipedia/commons/c/c9/Gudermannian_conformal_map.png)

**Comment by paulmasson** [comment]
@jrus nice work! Good to have the alternate method of evaluation recorded here. Thanks!

**Comment by jrus** [comment]
One reason to prefer the component version is that it better handles values very near the axes (including correctly handling real and/or imaginary part of `-0`). For example, the imaginary part of the gudermannian of $1 + 10^{-17}i$ gets rounded to 0 in your current implementation, but `Math.atanh(Math.sin(1e-17) / Math.cosh(1))` => 6.48e-18.

It also correctly handles the infinite endpoints of the strip. `gudermannian(complex(Infinity,0))` should return $\tfrac12\pi$, but the current implementation returns `{re: NaN, im: NaN}`.

(These problems might be evidence of bugs in your current complex-valued `tanh` and `arctan` implementation, rather than problems with implementing gudermannian this way per se. e.g. $\tanh(\infty + 0i)$ should be $1 + 0i$, not `NaN`.)
