### ISSUE TITLE
polylog - creates Uncaught InternalError: too much recursion

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#37]
Example:

```
console.log(polylog(new complex(2.0, 0.0),new complex(0.9993319736282411, 0.03654595031305655)));
```

See also:
- https://github.com/axkr/symja_android_library/issues/929

**Comment by paulmasson** [comment]
This should be fixed in [36a5d0e](https://github.com/paulmasson/math/commit/36a5d0eefc1506a1f5f36f2a80bfd04da11151d2). This is not the most elegant solution, since convergence is slow on the unit circle, but at least it returns a result.

@axkr let me know if you have any other issues with this function.
