### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#4]
Do you have any unit tests available for the implemented functions?

**Comment by paulmasson** [comment]
No unit tests yet. What did you have in mind?

**Comment by axkr** [comment]
I've searched for unit tests to check my Java port of the JavaScript functions.

**Comment by paulmasson** [comment]
@axkr finally getting around to adding some test apparatus. Since I want to have an immediate sense of the accuracy of functions, I created a repository for files of test data generated by mpmath,

https://github.com/paulmasson/math-test-data

and created a test page that compares the same calculation in this library:

https://paulmasson.github.io/math/test/complex-plane.html

You're welcome to use the compiled data files for testing your own function in Java. Let me know in that repository if you'd like something particular added.

@fredrik-johansson since I'm using mpmath as my standard, I thought you might like to know of the existence of this test page.

**Comment by paulmasson** [comment]
With the test apparatus in [1.3.0](https://github.com/paulmasson/math/releases/tag/1.3.0) this issue can be closed.
